/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import { useGLTF } from '@react-three/drei';
import Pedestal from './PEDESTAL.glb';

export default function Model(props) {
  const { nodes, materials } = useGLTF(Pedestal);
  return [{type:'raw',geometry:nodes.PEDESTAL.geometry,
         material:materials.Material_001}]




}

useGLTF.preload(Pedestal)
