/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';
import Pedestal_Link_Collision from './pedestal_link_collision.glb';


export default function Model(props) {
  const { nodes } = useGLTF(Pedestal_Link_Collision);
  return [{type:'raw', geometry:nodes['PEDESTAL-L'].geometry, material:nodes['PEDESTAL-L'].material}]
}

useGLTF.preload(Pedestal_Link_Collision)
