/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import Ur5Shoulder from "./shoulder.glb";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF(Ur5Shoulder);
  return [
    {
      type: "group",
      rotation: [-Math.PI,0,-Math.PI],
      children: [
        {
          type: "raw",
          geometry: nodes.eSeries_UR5e_001.geometry,
          material: materials["JointGrey.002"],
          scale: [0.001, 0.001, 0.001],
        },
        {
          type: "raw",
          geometry: nodes.eSeries_UR5e_007.geometry,
          material: materials["Black.002"],
          scale: [0.001, 0.001, 0.001],
        },
        {
          type: "raw",
          geometry: nodes.eSeries_UR5e_008.geometry,
          material: materials["URBlue.001"],
          scale: [0.001, 0.001, 0.001],
        },
      ],
    },
  ];
}

useGLTF.preload(Ur5Shoulder);
