/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import Ur5Upperarm from './upperarm.glb';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {

  const { nodes, materials } = useGLTF(Ur5Upperarm);
  return [
{type:'raw',geometry:nodes['ActorShape0_0-Mesh024'].geometry, material:nodes['ActorShape0_0-Mesh024'].material} ,
{type:'raw',geometry:nodes['ActorShape0_0-Mesh024_1'].geometry, material:nodes['ActorShape0_0-Mesh024_1'].material} ,
{type:'raw',geometry:nodes.Actor1.geometry, material:nodes.Actor1.material} ,
{type:'raw',geometry:nodes['ActorShape2_0-Mesh011'].geometry, material:nodes['ActorShape2_0-Mesh011'].material} ,
{type:'raw',geometry:nodes['ActorShape2_0-Mesh011_1'].geometry, material:nodes['ActorShape2_0-Mesh011_1'].material} ,
{type:'raw',geometry:nodes.Actor3.geometry, material:materials['Rohr.006']} ,
{type:'raw',geometry:nodes.Actor4.geometry, material:nodes.Actor4.material}

  ]
}

useGLTF.preload(Ur5Upperarm)
