/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import Ur5Wrist2 from "./wrist2.glb";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF(Ur5Wrist2);
  return [
    {
      type: 'group',
      rotation: [-Math.PI,0,-Math.PI],
      scale: [0.001, 0.001, 0.001],
      children: [
        {
          type: "raw",
          geometry: nodes.eSeries_UR5e_049.geometry,
          material: materials["JointGrey.006"],
        },
        {
          type: "raw",
          geometry: nodes.eSeries_UR5e_029.geometry,
          material: materials["URBlue.005"],
        },
        {
          type: "raw",
          geometry: nodes.eSeries_UR5e_002.geometry,
          material: materials["Black.006"],
        },
      ]
    }
    
  ];
}

useGLTF.preload(Ur5Wrist2);
