/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import Ur5Wrist3 from './wrist3.glb';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {

  const { nodes, materials } = useGLTF(Ur5Wrist3 )
  return [

{type:'raw', geometry:nodes['ActorShape0_0-Mesh003'].geometry,material:materials.Rohr_007_001} ,
{type:'raw', geometry:nodes['ActorShape0_0-Mesh003_1'].geometry, material:materials['SWMaterial-1_004_002_001']}
]

}

useGLTF.preload(Ur5Wrist3 )
