/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import Ur5Wrist1 from './wrist1.glb';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {
  const { nodes, materials } = useGLTF(Ur5Wrist1);
  return[
{type:'raw',geometry:nodes['ActorShape0_0-Mesh025'].geometry,material:materials.Scheibe_001} ,
{type:'raw',geometry:nodes['ActorShape0_0-Mesh025_1'].geometry, material:materials['verbindung_001.001']} ,
{type:'raw',geometry:nodes.Actor1.geometry, material:materials['blau_001.001']}

]
}

useGLTF.preload(Ur5Wrist1)
