/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import Ur5Wrist3 from "./wrist3.glb";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF(Ur5Wrist3);
  return [
    {
      type: "raw",
      geometry: nodes.eSeries_UR5e_058.geometry,
      material: materials["LinkGrey.003"],
      rotation: [-Math.PI,0,-Math.PI],
      scale: [0.001, 0.001, -0.001],
    },
  ];
}

useGLTF.preload(Ur5Wrist3);
