/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import Ur5Wrist1 from "./wrist1.glb";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF(Ur5Wrist1);
  return [
    {
      type:'group',
      rotation: [-Math.PI,0,-Math.PI],
      scale: [0.001, 0.001, 0.001],
      children:[
        {
          type: "raw",
          geometry: nodes.eSeries_UR5e_043.geometry,
          material: materials["JointGrey.005"],
        },
        {
          type: "raw",
          geometry: nodes.eSeries_UR5e_026.geometry,
          material: materials["URBlue.004"],
        },
        {
          type: "raw",
          geometry: nodes.eSeries_UR5e_027.geometry,
          material: materials["Black.005"],
        },
      ]
    }
    
  ];
}

useGLTF.preload(Ur5Wrist1);
