/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import { useGLTF } from '@react-three/drei';
import Ur3Forearm from './forearm.glb';

export default function Model(props) {

  const { nodes } = useGLTF(Ur3Forearm)
  return [
    { type: 'raw', geometry: nodes.eSeries_UR3e_033.geometry, material: nodes.eSeries_UR3e_033.material, scale:[0.001, 0.001, 0.001], rotation:[Math.PI/2, 0, 0]},
    { type: 'raw', geometry: nodes.eSeries_UR3e_022.geometry, material: nodes.eSeries_UR3e_022.material, scale:[0.001, 0.001, 0.001], rotation:[Math.PI/2, 0, 0]},
    { type: 'raw', geometry: nodes.eSeries_UR3e_023.geometry, material: nodes.eSeries_UR3e_023.material, scale:[0.001, 0.001, 0.001], rotation:[Math.PI/2, 0, 0]},
    { type: 'raw', geometry: nodes.eSeries_UR3e_024.geometry, material: nodes.eSeries_UR3e_024.material, scale:[0.001, 0.001, 0.001], rotation:[Math.PI/2, 0, 0]},
    { type: 'raw', geometry: nodes.eSeries_UR3e_025.geometry, material: nodes.eSeries_UR3e_025.material, scale:[0.001, 0.001, 0.001], rotation:[Math.PI/2, 0, 0]},
    { type: 'raw', geometry: nodes.eSeries_UR3e_026.geometry, material: nodes.eSeries_UR3e_026.material, scale:[0.001, 0.001, 0.001], rotation:[Math.PI/2, 0, 0]},
    { type: 'raw', geometry: nodes.eSeries_UR3e_028.geometry, material: nodes.eSeries_UR3e_028.material, scale:[0.001, 0.001, 0.001], rotation:[Math.PI/2, 0, 0]}
  ]
}

useGLTF.preload(Ur3Forearm)