/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import { useGLTF } from '@react-three/drei'
import Box from './Box.glb';

export default function Model(props) {
  const { nodes } = useGLTF(Box);
  return [{type:'raw',geometry:nodes.Box.geometry, material:nodes.Box.material}]

}

useGLTF.preload(Box)
