/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import { useGLTF } from '@react-three/drei';
import OpenWaypointMarker from './OpenWaypointMarker.glb';

export default function Model(props) {

  const { nodes } = useGLTF(OpenWaypointMarker)
  return [
    {
      type: 'group',
      children: [
        {
          type: 'raw',
          geometry:nodes.OpenWaypointMarker.geometry, 
          material:nodes.OpenWaypointMarker.material
        }
      ]
    }
]

}

useGLTF.preload(OpenWaypointMarker)
