/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import { useGLTF } from '@react-three/drei';
import RobotiqVisual85InnerFinger from './robotiq_arg2f_85_inner_finger.glb';

export default function Model(props) {
  const { nodes, materials } = useGLTF(RobotiqVisual85InnerFinger)
  return [
    {type:'raw', geometry:nodes.node0.geometry,material:materials['mymaterial.003']}
  ]
}

useGLTF.preload(RobotiqVisual85InnerFinger)
