/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import Hand from './hand.glb';

export default function Model(props) {
  const { nodes, materials } = useGLTF(Hand);
  return [
{type:'raw', geometry:nodes.node2.geometry,
material:materials.Part__Feature002_005_005},
{type:'raw', geometry:nodes.node5.geometry,
material:materials.Part__Feature005_001_005},
{type:'raw', geometry:nodes.node0.geometry,
material:materials.Part__Feature_009_005},
{type:'raw', geometry:nodes.node1.geometry,
material:materials.Part__Feature001_008_005},
{type:'raw', geometry:nodes.node5_001.geometry,
material:materials.Part__Feature005_001_005_001},
]



}

useGLTF.preload(Hand)
