/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import Link3 from "./link3.glb";

export default function Model(props) {
  const { nodes, materials } = useGLTF(Link3);
  return [
    {
      type: "group",
      // rotation: [-Math.PI / 2, -Math.PI / 2, -Math.PI / 2],
      // rotation: [-Math.PI / 2, -Math.PI / 2, Math.PI / 2],
      // rotation: [-Math.PI / 2, Math.PI / 2, Math.PI / 2],
      // rotation: [Math.PI / 2, Math.PI / 2, Math.PI / 2],
      // rotation: [Math.PI / 2, Math.PI / 2, -Math.PI / 2],
      // rotation: [Math.PI / 2, -Math.PI / 2, -Math.PI / 2],
      // rotation: [-Math.PI / 2, Math.PI / 2, -Math.PI / 2],
      rotation: [Math.PI/2, Math.PI, Math.PI],
      position: [0, -0.12, 0],
      children: [
        {
          type: "raw",
          geometry: nodes.node0_001.geometry,
          material: materials.Part__Feature_001_001_001_002
        },
        {
          type: "raw",
          geometry: nodes.node1.geometry,
          material: materials.Part__Feature001_010_001_002
        },
        {
          type: "raw",
          geometry: nodes.node2.geometry,
          material: materials.Part__Feature002_007_001_002
        },
        {
          type: "raw",
          geometry: nodes.node3.geometry,
          material: materials.Part__Feature003_004_001_002
        },
      ],
    },
  ];
}

useGLTF.preload(Link3);
