/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import { useGLTF } from '@react-three/drei'
import mesh from './RThumb1.glb'

export default function Model() {
 
  const { nodes, materials } = useGLTF(mesh)

  return [{
    type : 'group', children : [{type : 'raw' ,geometry : nodes.RThumb1_010.geometry, material : nodes.RThumb1_010.material }]
  }]

 

    
}

useGLTF.preload(mesh)
