/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import mesh from './WheelFR.glb'
export default function Model() {
  const group = useRef()
  const { nodes, materials } = useGLTF(mesh)

  return [{
    type : 'group', children : [{type : 'raw' ,geometry : nodes.WheelFR_010.geometry, material : nodes.WheelFR_010.material }]
  }]


  
     
}

useGLTF.preload(mesh)
