/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import Ur10Upperarm from './upperarm.glb';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {

  const { nodes, materials } = useGLTF(Ur10Upperarm)
  return[
{type:'raw',geometry:nodes['node-shape0-name'].geometry,material:materials['SWMaterial-0.003']} ,
{type:'raw',geometry:nodes['node-shape1-name'].geometry, material:materials['SWMaterial-1.003']} ,
{type:'raw',geometry:nodes['node-shape2-name'].geometry, material:materials['SWMaterial-2.003']} ,
{type:'raw',geometry:nodes['node-shape3-name'].geometry, material:materials['SWMaterial-3.002']}


]
}
useGLTF.preload(Ur10Upperarm)
