/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import Ur3Base from './base.glb';
import { useGLTF } from '@react-three/drei'


export default function Model(props) {
  const { nodes} = useGLTF(Ur3Base)
  return [{type:'raw',geometry:nodes.base.geometry,material: nodes.base.material}]
}

useGLTF.preload(Ur3Base)
