/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import Ur3Forearm from './forearm.glb';
import { useGLTF } from '@react-three/drei'

export default function Model(props ) {
  const { nodes } = useGLTF(Ur3Forearm);
  return [{type:'raw',geometry:nodes.forearm.geometry,material:nodes.forearm.material}]
  
}

useGLTF.preload(Ur3Forearm);
