/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import Ur3Shoulder from './shoulder.glb';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {
  const { nodes} = useGLTF(Ur3Shoulder);
  return [{type:'raw', geometry:nodes.shoulder.geometry, material: nodes.shoulder.material}]
  
}

useGLTF.preload(Ur3Shoulder)
