/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import Ur3Wrist3 from './wrist3.glb';
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes} = useGLTF(Ur3Wrist3)
  return [{type:'raw',geometry:nodes.wrist3.geometry, material:nodes.wrist3.material}]
}

useGLTF.preload(Ur3Wrist3);
