/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import Ur3Wrist2 from './wrist2.glb';
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes} = useGLTF(Ur3Wrist2);
  return [{type:'raw',geometry:nodes.wrist2.geometry,material:nodes.wrist2.material}]  
}

useGLTF.preload(Ur3Wrist2);
