/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';
import LElbowRollMesh from './LElbowRoll.glb';

export default function Model(props) {
  const { nodes, materials } = useGLTF(LElbowRollMesh);
  return [{type:'raw',geometry:nodes.LElbowRoll.geometry, material:materials.LElbowRollUV, scale:[0.01, 0.01, 0.01]}]


}

useGLTF.preload(LElbowRollMesh);
