/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';
import LFinger21Mesh from './LFinger21.glb';
export default function Model(props) {
  const { nodes, materials } = useGLTF(LFinger21Mesh);
  return [{type:'raw',geometry:nodes.LFinger21.geometry, material:materials.LFinger21UV, scale:[0.01, 0.01, 0.01]}]




}

useGLTF.preload(LFinger21Mesh)
