/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';
import LFinger13Mesh from './LFinger13.glb';

export default function Model(props) {
  const { nodes, materials } = useGLTF(LFinger13Mesh);
  return [{ type:'raw', geometry: nodes.LFinger13.geometry, material:materials.Lfindger13UV, scale:[0.01, 0.01, 0.01]}]


}

useGLTF.preload(LFinger13Mesh);
