/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';
import LThumb1Mesh from './LThumb1.glb';


export default function Model(props) {
  const { nodes, materials } = useGLTF(LThumb1Mesh);
  return [{type:'raw',geometry:nodes.LThumb1.geometry, material:materials.LThumb1UV, scale:[0.01, 0.01, 0.01]}]
}

useGLTF.preload(LThumb1Mesh);
