/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';
import LWristYawMesh from './LWristYaw.glb';

export default function Model(props) {
  const { nodes, materials } = useGLTF(LWristYawMesh);
  return [{type:'raw',geometry:nodes.RWristYaw.geometry, material:materials.RWristYawUV, scale:[0.01, 0.01, 0.01]}]
}

useGLTF.preload(LWristYawMesh)
