/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';
import RAnkleRollMesh from './RAnkleRoll.glb';

export default function Model(props) {
  const { nodes, materials } = useGLTF(RAnkleRollMesh);
  return [{type:'raw',geometry:nodes.RAnkleRoll.geometry, material:materials.RAnkleRollUV, scale:[0.01, 0.01, 0.01]}]
}

useGLTF.preload(RAnkleRollMesh)
