/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import { useGLTF } from '@react-three/drei';
import RFinger22Mesh from './RFinger22.glb';


export default function Model(props) {

  const { nodes, materials } = useGLTF(RFinger22Mesh);
  return [
 {type:'raw',geometry:nodes.RFinger21.geometry,material:materials.RFinger21UV,scale:[0.01, 0.01, 0.01]},
 {type:'raw',geometry:nodes.RFinger22.geometry,material:materials.RFinger22UV,scale:[0.01, 0.01, 0.01]},
]

}

useGLTF.preload(RFinger22Mesh)
