/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import { useGLTF } from '@react-three/drei';
import RFinger23Mesh from './RFinger23.glb';

export default function Model(props) {
  const { nodes, materials } = useGLTF(RFinger23Mesh);
  return [{type:'raw', geometry:nodes.RFinger23.geometry, material:materials.RFinger23UV, scale:[0.01, 0.01, 0.01]}]



}

useGLTF.preload(RFinger23Mesh)
