/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import { useGLTF } from '@react-three/drei';
import RKneePitchMesh from './RKneePitch.glb';

export default function Model(props) {
  const { nodes, materials } = useGLTF(RKneePitchMesh);
  return [{type:'raw', geometry:nodes.RKneePitch.geometry, material:materials.uvAnkle, scale:[0.01, 0.01, 0.01]}]
}

useGLTF.preload(RKneePitchMesh)
