/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';
import RThumb2Mesh from './RThumb2.glb';

export default function Model(props) {
  const { nodes, materials } = useGLTF(RThumb2Mesh);
  return [{  type:'raw', geometry:nodes.RThumb2.geometry, material:materials.RThumb2UV, scale:[0.01, 0.01, 0.01]}]
}

useGLTF.preload(RThumb2Mesh)
