name: CI
on: push

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64, i686]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.9
        architecture: x64
    - name: Build wheels
      uses: PyO3/maturin-action@v1
      with:
        target: ${{ matrix.target }}
        manylinux: auto
        args: --release --out dist
    - name: Install built wheel
      if: matrix.target == 'x86_64'
      run: |
        pip install lively --no-index --find-links dist --force-reinstall
        python -c "import lively"
    - name: Upload wheels
      uses: actions/upload-artifact@v3
      with:
        name: wheels
        path: dist
  # test-macos:
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-python@v4
  #       with:
  #         python-version: 3.9
  #         architecture: x64
  #     - uses: dtolnay/rust-toolchain@stable
  #     - name: Build wheels - x86_64
  #       uses: PyO3/maturin-action@v1
  #       with:
  #         target: x86_64
  #         args: --release --out dist
  #     - name: Install built wheel - x86_64
  #       run: |
  #         pip install lively --no-index --find-links dist --force-reinstall
  #         python -c "import lively"
  #     - name: Build wheels - universal2
  #       uses: PyO3/maturin-action@v1
  #       with:
  #         args: --release --universal2
  #     - name: Install built wheel - universal2
  #       run: |
  #         pip install lively --no-index --find-links dist --force-reinstall
  #         python -c "import lively"
  #     - name: Upload wheels
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: wheels
  #         path: dist